// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: pkg/api/v1beta1/shim.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CiphertextWithKEK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ciphertext []byte `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Kek        []byte `protobuf:"bytes,2,opt,name=kek,proto3" json:"kek,omitempty"`
}

func (x *CiphertextWithKEK) Reset() {
	*x = CiphertextWithKEK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_v1beta1_shim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CiphertextWithKEK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiphertextWithKEK) ProtoMessage() {}

func (x *CiphertextWithKEK) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1beta1_shim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiphertextWithKEK.ProtoReflect.Descriptor instead.
func (*CiphertextWithKEK) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1beta1_shim_proto_rawDescGZIP(), []int{0}
}

func (x *CiphertextWithKEK) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *CiphertextWithKEK) GetKek() []byte {
	if x != nil {
		return x.Kek
	}
	return nil
}

var File_pkg_api_v1beta1_shim_proto protoreflect.FileDescriptor

var file_pkg_api_v1beta1_shim_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2f, 0x73, 0x68, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x22, 0x45, 0x0a, 0x11, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74,
	0x65, 0x78, 0x74, 0x57, 0x69, 0x74, 0x68, 0x4b, 0x45, 0x4b, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69,
	0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x6b, 0x42, 0x2d, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x62, 0x69, 0x68, 0x69,
	0x6d, 0x2f, 0x6b, 0x6d, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_v1beta1_shim_proto_rawDescOnce sync.Once
	file_pkg_api_v1beta1_shim_proto_rawDescData = file_pkg_api_v1beta1_shim_proto_rawDesc
)

func file_pkg_api_v1beta1_shim_proto_rawDescGZIP() []byte {
	file_pkg_api_v1beta1_shim_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1beta1_shim_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_v1beta1_shim_proto_rawDescData)
	})
	return file_pkg_api_v1beta1_shim_proto_rawDescData
}

var file_pkg_api_v1beta1_shim_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_api_v1beta1_shim_proto_goTypes = []interface{}{
	(*CiphertextWithKEK)(nil), // 0: v1beta1.CiphertextWithKEK
}
var file_pkg_api_v1beta1_shim_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_v1beta1_shim_proto_init() }
func file_pkg_api_v1beta1_shim_proto_init() {
	if File_pkg_api_v1beta1_shim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_v1beta1_shim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CiphertextWithKEK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_v1beta1_shim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_v1beta1_shim_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1beta1_shim_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1beta1_shim_proto_msgTypes,
	}.Build()
	File_pkg_api_v1beta1_shim_proto = out.File
	file_pkg_api_v1beta1_shim_proto_rawDesc = nil
	file_pkg_api_v1beta1_shim_proto_goTypes = nil
	file_pkg_api_v1beta1_shim_proto_depIdxs = nil
}
